import = []

[default_session]
preview_command = "ls -la {}"

[[session]]
name = "home "
path = "~"

[[session]]
name = "code "
path = "~/code"

[[session]]
name = "nixos 󱄅"
path = "~/nixos"

[[session]]
name = "downloads "
path = "~/Downloads"

